### ISSUE TITLE
使用DynamicController重复加载Controller会发生异常

### ISSUE THREAD

**Issue by aaguojing** [wb04307201/loader-util#1]
使用示例代码时，
使用DynamicController重复加载Controller会发生异常
异常如下
![图片](https://github.com/wb04307201/loader-util/assets/65690222/a0e82bdb-1187-41fe-95e8-477c51c196c2)

**Comment by wb04307201** [comment]
1.1.1版本修复该问题
修正controller加载方法
在加载之前先卸载url映射和bean
然后再加载controller
![image](https://github.com/wb04307201/loader-util/assets/35208417/91abb7a1-e900-4836-82dc-50b6205d22bf)
